//* Login
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REGISTER_USER_START = 'REGISTER_USER_START'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const CHECK_USER_AUTH_SUCCESS = 'CHECK_USER_AUTH_SUCCESS'

//* Error
export const ERROR = 'ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

//* Notification
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW'
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE'

//* Users
export const GET_USER_DATA_START = 'GET_USER_DATA_START'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const UPDATE_USER_DATA_START = 'UPDATE_USER_DATA_START'
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS'
export const SEND_NEW_CREDENTIALS_START = 'SEND_NEW_CREDENTIALS_START'
export const SEND_NEW_CREDENTIALS_SUCCESS = 'SEND_NEW_CREDENTIALS_SUCCESS'
export const UPDATE_USER_PHOTO_START = 'UPDATE_USER_PHOTO_START'
export const UPDATE_USER_PHOTO_SUCCESS = 'UPDATE_USER_PHOTO_SUCCESS'
export const SEND_USER_POSITION_START = 'SEND_USER_POSITION_START'
export const SEND_USER_POSITION_SUCCESS = 'SEND_USER_POSITION_SUCCESS'
export const UPDATE_USER_DELIVERY_START = 'UPDATE_USER_DELIVERY_START'
export const UPDATE_USER_DELIVERY_SUCCESS = 'UPDATE_USER_DELIVERY_SUCCESS'

//* Support
export const GET_SUPPORT_MESSAGES_START = 'GET_SUPPORT_MESSAGES_START'
export const GET_SUPPORT_MESSAGES_SUCCESS = 'GET_SUPPORT_MESSAGES_SUCCESS'
export const GET_ONE_SUPPORT_MESSAGE_START = 'GET_ONE_SUPPORT_MESSAGE_START'
export const GET_ONE_SUPPORT_MESSAGE_SUCCESS = 'GET_ONE_SUPPORT_MESSAGE_SUCCESS'

//* Delivery
export const CREATE_NEW_DELIVERY_START = 'CREATE_NEW_DELIVERY_START'
export const CREATE_NEW_DELIVERY_SUCCESS = 'CREATE_NEW_DELIVERY_SUCCESS'
export const GET_ALL_USER_DELIVERY_SUCCESS = 'GET_ALL_USER_DELIVERY_SUCCESS'
export const GET_ALL_USER_DELIVERY_START = 'GET_ALL_USER_DELIVERY_START'
export const GET_DELIVERY_SUCCESS = 'GET_DELIVERY_SUCCESS'
export const GET_DELIVERY_START = 'GET_DELIVERY_START'
export const ADD_PACKAGE_TO_DELIVERY_SUCCESS = 'ADD_PACKAGE_TO_DELIVERY_SUCCESS'
export const ADD_PACKAGE_TO_DELIVERY_START = 'ADD_PACKAGE_TO_DELIVERY_START'
export const GET_PACKAGE_DATA_SUCCESS = 'GET_PACKAGE_DATA_SUCCESS'
export const GET_PACKAGE_DATA_START = 'GET_PACKAGE_DATA_START'
export const UPDATE_PACKAGE_DATA_IN_DELIVERY_SUCCESS = 'UPDATE_PACKAGE_DATA_IN_DELIVERY_SUCCESS'
export const UPDATE_DELIVERY_STATUS_SUCCESS = 'UPDATE_DELIVERY_STATUS_SUCCESS'
export const UPDATE_DELIVERY_STATUS_START = 'UPDATE_DELIVERY_STATUS_START'
export const UPDATE_DELIVERY_PACKAGE_STATUS_SUCCESS = 'UPDATE_DELIVERY_PACKAGE_STATUS_SUCCESS'
export const UPDATE_DELIVERY_PACKAGE_STATUS_START = 'UPDATE_DELIVERY_PACKAGE_STATUS_START'
